### ISSUE TITLE
Can't save database

### ISSUE THREAD

**Issue by rmwiseman** [keepassxreboot/keepassxc-packaging#10]
I'm using KeePassXC installed as a Flatpak on Linux Mint 18.3 (Ubuntu 16.04 base).  My database is in my Dropbox folder but when I try to save, it fails, showing an error:

> Writing the database failed.
> Cannot create /run/user/1000/doc/2d696d13/passwords.kdbx for output

I've attached a (redacted) screen grab too:

![screenshot from 2018-05-24 10-28-06 blurred](https://user-images.githubusercontent.com/10866705/40477523-8de6e938-5f3e-11e8-82f4-35c858897644.png)

As I indicated, the path in the error is not where my database file actually lives, so I don't know what the problem is.

**Comment by rmwiseman** [comment]
I've now also tried having the database elsewhere.  Whenever I open it, it disappears from where it should be and (I think) appears in `/run/user/1000/doc/something`.  Even if I try to "Save As..." somewhere else, it fails with a similar error.

**Comment by phoerious** [comment]
Flatpaks are not provided by us. Please use the AppImage or Snap package. There are multiple known issues with Flatpaks. See https://github.com/keepassxreboot/keepassxc/issues/1524

**Comment by RoyiAvital** [comment]
Use `--filesystem=home` flag to run it.
Then you will be able to save and load data base from the user folder.

**Comment by rmwiseman** [comment]
Thanks for the tip @RoyiAvital but when I include `--filesystem=home` I still get the same error when trying to save.

**Comment by joanmarcriera** [comment]
same here .
