### ISSUE TITLE
Missidentify current version during update

### ISSUE THREAD

**Issue by dbolton** [keepassxreboot/keepassxc-packaging#11]
Steps to reproduce
1. Install KeePassXC 2.3.3
2. Install KeePassXC 2.3.4

Actual behavior
At the start of install for 2.3.4, a dialog pops up saying
> KeePassXC v2.3.4 is already installed. 
> 
> Do you want to uninstall the old version before installing the new one? 

Expected behavior
The dialog should either specify the correct version number for the application that is already installed or just drop the version information by saying
> KeePassXC is already installed. 
> 
> Do you want to uninstall the old version before installing the new one? 

(Windows 10, 64-bit)

**Comment by droidmonkey** [comment]
We know, already reported thanks.
