### ISSUE TITLE
No deb package for incoming ubuntu 20.04 (focal) release

### ISSUE THREAD

**Issue by DuMaM** [keepassxreboot/keepassxc-packaging#15]
## Expected Behavior
sudo add-apt-repository ppa:phoerious/keepassxc
sudo apt update

-> success

## Current Behavior
Error:11 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading pacage list... Ready
E: The repository 'http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal Release' does not have a Release file.

## Possible Solution
Add file for focal release in ppa

## Steps to Reproduce
Self-Explanatory

## Context
Small mess in apt source list

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - N/A
Revision: N/A

Operating system: OS
CPU architecture: amd64
Kernel: 5.4.0-21-generic

Enabled extensions:
- none

**Comment by phoerious** [comment]
PPA has been updated with new 2.5.4 release.
