### ISSUE TITLE
[RFC] Creating immutable build env

### ISSUE THREAD

**Issue by mattyjones** [keepassxreboot/keepassxc-packaging#2]
For now I am using the inline shell provisioner which is fast, very dirty, and does not scale. In the near future I would like to implement Ansible as the provisioner to cure the above issues. Using Vagrant I feel goes w/o saying but I am open to suggestions and comments.

### PROS

- immutability is fairly easy to obtain by following best practices
- one of the industry standards for configuring environments
- cross-platform (WIN, OSX, BSD, LINUX)
- good orchestrator as well if needed

### CONS
- somewhat specialized knowledge needed to maintain provisioner
- additional tool brought into the mix
- requires developer to have Ansible/Python env in order to use

**Comment by mattyjones** [comment]
Closing this as it has been 6+ months and no comments. I am going to assume that there are no objections and will continue to move forward with a build env for both debian and centos/rhel

**Comment by phoerious** [comment]
You may also want to have a look at this: https://ftp-master.debian.org/new/keepassxc_2.2.0-1.html
