### ISSUE TITLE
deb.sury.org PPA incompatibility for libargon2-0

### ISSUE THREAD

**Issue by rask** [keepassxreboot/keepassxc-packaging#8]
Hello.

I received an update to `libargon2-0` from this PPA today. I also use a 3rd party PPA (deb.sury.org) for installing multiple versions of the PHP programming language interpreter and tooling. PHP comes bundled with a built-in libsodium extension which contains an implementation for libargon2.

Today after a package upgrade run a file called `libargon2.so.0` went missing from my system and PHP stopped working as it relies on that file.

The PPA I use for PHP contains its own dependency for libargon2-0. I forced a "downgrade" to the PHP PPA version and PHP started working normally again.

Question: would using the PHP PPA version of libargon2 break KeepassXC in some way and should I find some other way to install either KeepassXC or PHP?

I raised an issue to the PHP PPA as well about this: https://github.com/oerdnj/deb.sury.org/issues/824

(I am not a Linux/Ubuntu expert so I do not know how PPA dependencies work in situations like this.)

**Comment by phoerious** [comment]
Since both packages provide SO version 0, they should be compatible.
I think this is a packaging error. libargon2 should provide libargon2.so.0. I'll make an upgrade.

**Comment by phoerious** [comment]
I updated the packages, they should not conflict anymore.

**Comment by rask** [comment]
I'll re-update and see what happens. Many thanks!

EDIT: Yup, works normally now. Thanks again. :+1:
