### ISSUE TITLE
libsodium18 vs libsodium23

### ISSUE THREAD

**Issue by PRESFIL** [keepassxreboot/keepassxc-packaging#9]
During the last update of the keepassxc up to 2.3, the dependence libsodium23 violates the other:
`E: /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb: attempt to overwrite «/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0», which is already in the package libsodium18:amd64 1.0.16-0ppa1~xenial1`
I tried to put the package manually from [https://launchpad.net/ubuntu/+source/libsodium](url)  before setting the keepassxc but it violates libc6 and so on ...
What's the point of putting libsodium23 if the same binaries exist in libsodium18 or is it another binary? Is there a need specifically in version 18 and how are things in other distributions?
Linux Mint 18.3 Cinnamon amd64 + KeePassXC 2.3.0-0ppa1~xenial

**Comment by RealOrangeOne** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/1545

**Comment by phoerious** [comment]
Please downgrade libsodium18 before installing libsodium23. See solution in the above-linked report.
